version: '3.8'

# Development override configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  android-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DEBUG=*
    volumes:
      # Mount source code for hot reload
      - ./server.js:/app/server.js
      - ./public:/app/public
      - ./package.json:/app/package.json
    command: ["npm", "run", "dev"]

  # Remove nginx in development
  nginx:
    profiles:
      - disabled